# Generated by Django 6.0.3 on 2026-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('subject_specialty', models.CharField(max_length=100)),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/')),
            ],
        ),
    ]
