# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=20)),
                ('session', models.CharField(choices=[('Matin', 'Matin (08:30 - 12:30)'), ('Soir', 'Soir (14:00 - 18:00)')], max_length=10)),
                ('group', models.CharField(choices=[('AD-S1', 'AD - S1'), ('AD-S2', 'AD - S2'), ('IDAI-S1', 'IDAI - S1'), ('IDAI-S2', 'IDAI - S2')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
